org.gradle.jvmargs=-Xmx1g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

group=org.fintrax
version=0.1.0-SNAPSHOT

javafxVersion=21.0.2
springBootVersion=3.5.15
hbci4javaVersion=4.1.11
eclipsestoreVersion=4.1.0
slf4jVersion=2.0.12
logbackVersion=1.4.14
lombokVersion=1.18.30
junitVersion=5.10.2
atlantafxVersion=2.0.1
testfxVersion=4.0.18
